title: "Welcome to ilssear's GitHub.io pages"
description: "Exploring physics and cognition through quantum and AI."
markdown: kramdown
theme: minima

defaults:
  - scope:
      path: ""
      type: "README"
    values:
      permalink: /
